<?php
session_start();

include 'includes/Autoloader.inc.php';
include 'includes/Constants.inc.php';

$productController = new ProductsController();
$colorFilter = $productController->getColorList();

$filter = (isset($_POST['filterColor'])) ? $_POST['filterColor'] : null;
?>

<!DOCTYPE html>
<html lang="eng">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Candy Shop</title>

    <link rel="stylesheet" type="text/css" href="css/styles.css">
    <link href="https://fonts.googleapis.com/css?family=Emilys+Candy&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto:500&display=swap" rel="stylesheet">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script language="javascript" type="text/javascript" src="js/script.js"></script>
</head>
<body>
<header>
    <div id="logo">
        <a href="#">
            <img src="images/Logo.jpg" alt="Logo">
        </a>
    </div>

    <nav id="nav">
        <ul>
            <?php if ($_SERVER['PHP_SELF'] === '/candyshop/basket.php'): ?>
                <li>
                    <p>Artikel im Warenkorb: <strong><?php echo count($_SESSION['basket']); ?></strong></p>
                </li>
                <li><a href="http://localhost:8080/candyshop/">Zurück zum Shop</a></li>
            <?php else : ?>
                <li>
                    <form action="http://localhost:8080/candyshop/" method="post">
                        <label>Filter:
                            <select id="colorFilter" name="filterColor" size="1">

                                <option disabled <?php echo (!is_null($filter)) ? 'selected': ''; ?>>
                                    Color
                                </option>
                                <option <?php echo ($filter == 'All') ? 'selected': ''; ?>>
                                    All
                                </option>
                                <?php foreach ($colorFilter as $color) : ?>
                                    <option <?php echo ($color == $filter) ? 'selected': ''; ?>>
                                        <?php echo $color; ?>
                                    </option>
                                <?php endforeach; ?>
                            </select>
                        </label>
                    </form>
                </li>
                <li><a href="http://localhost:8080/candyshop/basket.php">Warenkorb</a></li>
            <?php endif; ?>

        </ul>
    </nav>
</header>
<main>